### PR TITLE
Windows compatibility fixes

### PR DESCRIPTION
**Pull request by olehermanse**
More work needed but this helps for now.

### CODE REVIEW

**Comment by olehermanse** [comment]
```
make download
make responses
make scales
make json
make divide
```

**Comment by Berstad** [comment]
```
fui-kk> make responses
python scripts/responses.py -s all
Traceback (most recent call last):
  File "scripts/responses.py", line 107, in <module>
    main()
  File "scripts/responses.py", line 102, in main
    args = get_args()
  File "scripts/responses.py", line 32, in get_args
    dirs = next(os.walk('data'))[1]
StopIteration
make.exe": *** [responses] Error 1
```

**Comment by olehermanse** [comment]
@Berstad please review :)

**Review by Berstad — APPROVED** [review]
Seems to work fine now. No errors are generated.

**Pull request merged**
