### PR TITLE
New colours to Likert scale

### PR DESCRIPTION
**Pull request by PrebenAas**
Added new colours to the Likert scale to easier separate gradients. Hopefully better for colour blindness.

### CODE REVIEW

**Comment by PrebenAas** [comment]
please review @olehermanse @Berstad @evestera

**Comment by PrebenAas** [comment]
colorscales2

**Review by Berstad — APPROVED** [review]
This looks good to me! Seems to be about as good a compromise as we are going to get between optimization for color-blind and normal vision. Although there seems to be a conflict which must be fixed.

**Comment by PrebenAas** [comment]
@olehermanse can you take a look at the conflicting file? I don't have write access.

**Comment by olehermanse** [comment]
yes I will take a look when I have time. (Or you can edit the new file, which is in fui_kk/web_reports) and open another PR.

**Pull request merged**
