### PR TITLE
Finalizing report generation.

### PR DESCRIPTION
**Pull request by olehermanse**
Easiest to review commit by commit.

Added haakomols updated front page. Moved tex folders into resources to clean up in root dir.

### CODE REVIEW

**Comment by olehermanse** [comment]
Implemented requested changes to report:
 * Italicized quotes
 * New page for every course
 * Removed the red "korrrektur" in title

**Comment by olehermanse** [comment]
Added a bunch of smaller changes discovered while finishing report.

**Comment by olehermanse** [comment]
@evestera Please review

**Review by evestera — APPROVED** [review]
Looks good (except for missing author in participation_summary, but can always fix that later)

**Pull request merged**
